[2024-01-18T23:17:13.378+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:17:08.892435+00:00 [queued]>
[2024-01-18T23:17:13.386+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:17:08.892435+00:00 [queued]>
[2024-01-18T23:17:13.387+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:17:13.400+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-18 23:17:08.892435+00:00
[2024-01-18T23:17:13.404+0000] {standard_task_runner.py:57} INFO - Started process 4027 to run task
[2024-01-18T23:17:13.408+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'manual__2024-01-18T23:17:08.892435+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmpmztnid6o']
[2024-01-18T23:17:13.410+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask submit_spark_job
[2024-01-18T23:17:13.479+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:17:08.892435+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:17:13.586+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T23:17:08.892435+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T23:17:08.892435+00:00'
[2024-01-18T23:17:13.598+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:17:13.599+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:17:13.762+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:17:19.612+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:19.611601: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-01-18T23:17:19.719+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:19.719298: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:17:20.251+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:20.250919: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[2024-01-18T23:17:20.251+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:20.251075: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[2024-01-18T23:17:20.360+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:20.359745: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-01-18T23:17:20.602+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:20.601915: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:17:20.603+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:20.603576: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-01-18T23:17:20.603+0000] {spark_submit.py:571} INFO - To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-01-18T23:17:22.679+0000] {spark_submit.py:571} INFO - 2024-01-18 23:17:22.678715: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-18T23:17:28.179+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SparkContext: Running Spark version 3.5.0
[2024-01-18T23:17:28.185+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SparkContext: OS info Linux, 5.10.102.1-microsoft-standard-WSL2, amd64
[2024-01-18T23:17:28.186+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SparkContext: Java version 11.0.21
[2024-01-18T23:17:28.322+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-18T23:17:28.489+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO ResourceUtils: ==============================================================
[2024-01-18T23:17:28.489+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-18T23:17:28.489+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO ResourceUtils: ==============================================================
[2024-01-18T23:17:28.490+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SparkContext: Submitted application: SparkDataStreaming
[2024-01-18T23:17:28.529+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-18T23:17:28.554+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO ResourceProfile: Limiting resource is cpu
[2024-01-18T23:17:28.555+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-18T23:17:28.674+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SecurityManager: Changing view acls to: ***
[2024-01-18T23:17:28.677+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SecurityManager: Changing modify acls to: ***
[2024-01-18T23:17:28.677+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SecurityManager: Changing view acls groups to:
[2024-01-18T23:17:28.677+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SecurityManager: Changing modify acls groups to:
[2024-01-18T23:17:28.677+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:28 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-01-18T23:17:29.098+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO Utils: Successfully started service 'sparkDriver' on port 37779.
[2024-01-18T23:17:29.158+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO SparkEnv: Registering MapOutputTracker
[2024-01-18T23:17:29.232+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-18T23:17:29.272+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-18T23:17:29.273+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-18T23:17:29.280+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-18T23:17:29.329+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-602167a3-1ad3-434d-a9f5-e30841025680
[2024-01-18T23:17:29.352+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-18T23:17:29.384+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-18T23:17:29.678+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-18T23:17:29.815+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-18T23:17:29.985+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:29 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.29.0.5:7077...
[2024-01-18T23:17:30.065+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:30 INFO TransportClientFactory: Successfully created connection to /172.29.0.5:7077 after 45 ms (0 ms spent in bootstraps)
[2024-01-18T23:17:31.922+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240118231731-0000
[2024-01-18T23:17:31.934+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41359.
[2024-01-18T23:17:31.934+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO NettyBlockTransferService: Server created on 36e53310e6a3:41359
[2024-01-18T23:17:31.938+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-01-18T23:17:31.950+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 36e53310e6a3, 41359, None)
[2024-01-18T23:17:31.954+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO BlockManagerMasterEndpoint: Registering block manager 36e53310e6a3:41359 with 434.4 MiB RAM, BlockManagerId(driver, 36e53310e6a3, 41359, None)
[2024-01-18T23:17:31.957+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 36e53310e6a3, 41359, None)
[2024-01-18T23:17:31.959+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:31 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 36e53310e6a3, 41359, None)
[2024-01-18T23:17:32.048+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:32 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118231731-0000/0 on worker-20240118223130-172.29.0.7-36307 (172.29.0.7:36307) with 2 core(s)
[2024-01-18T23:17:32.050+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:32 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118231731-0000/0 on hostPort 172.29.0.7:36307 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:17:32.060+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:32 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118231731-0000/1 on worker-20240118223130-172.29.0.8-39635 (172.29.0.8:39635) with 2 core(s)
[2024-01-18T23:17:32.063+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:32 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118231731-0000/1 on hostPort 172.29.0.8:39635 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:17:32.277+0000] {spark_submit.py:571} INFO - 24/01/18 23:17:32 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-01-18T23:17:32.598+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['localhost'], lbp = None)
[2024-01-18T23:17:32.610+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:[control connection] Error connecting to 127.0.0.1:9042:
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3541, in cassandra.cluster.ControlConnection._reconnect_internal
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3563, in cassandra.cluster.ControlConnection._try_connect
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 1630, in cassandra.cluster.Cluster.connection_factory
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - File "cassandra/connection.py", line 850, in cassandra.connection.Connection.factory
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/cassandra/io/asyncorereactor.py", line 347, in __init__
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - self._connect_socket()
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - File "cassandra/connection.py", line 917, in cassandra.connection.Connection._connect_socket
[2024-01-18T23:17:32.611+0000] {spark_submit.py:571} INFO - ConnectionRefusedError: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:[control connection] Error connecting to ::1:9042:
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3541, in cassandra.cluster.ControlConnection._reconnect_internal
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3563, in cassandra.cluster.ControlConnection._try_connect
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 1630, in cassandra.cluster.Cluster.connection_factory
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - File "cassandra/connection.py", line 850, in cassandra.connection.Connection.factory
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/cassandra/io/asyncorereactor.py", line 347, in __init__
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - self._connect_socket()
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - File "cassandra/connection.py", line 917, in cassandra.connection.Connection._connect_socket
[2024-01-18T23:17:32.612+0000] {spark_submit.py:571} INFO - OSError: [Errno 99] Tried connecting to [('::1', 9042, 0, 0)]. Last error: Cannot assign requested address
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - ERROR:cassandra.cluster:Control connection failed to connect, shutting down Cluster:
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 1700, in cassandra.cluster.Cluster.connect
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3507, in cassandra.cluster.ControlConnection.connect
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3552, in cassandra.cluster.ControlConnection._reconnect_internal
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused"), '::1:9042': OSError(99, "Tried connecting to [('::1', 9042, 0, 0)]. Last error: Cannot assign requested address")})
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 132, in <module>
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - batch_processing()
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 68, in batch_processing
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - session = cluster.connect()
[2024-01-18T23:17:32.613+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 1677, in cassandra.cluster.Cluster.connect
[2024-01-18T23:17:32.614+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 1713, in cassandra.cluster.Cluster.connect
[2024-01-18T23:17:32.614+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 1700, in cassandra.cluster.Cluster.connect
[2024-01-18T23:17:32.614+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3507, in cassandra.cluster.ControlConnection.connect
[2024-01-18T23:17:32.614+0000] {spark_submit.py:571} INFO - File "cassandra/cluster.py", line 3552, in cassandra.cluster.ControlConnection._reconnect_internal
[2024-01-18T23:17:32.614+0000] {spark_submit.py:571} INFO - cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused"), '::1:9042': OSError(99, "Tried connecting to [('::1', 9042, 0, 0)]. Last error: Cannot assign requested address")})
[2024-01-18T23:17:34.260+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:17:34.271+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240118T231708, start_date=20240118T231713, end_date=20240118T231734
[2024-01-18T23:17:34.288+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 4027)
[2024-01-18T23:17:34.313+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:17:34.328+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
